# Generated by Django 4.1.2 on 2022-10-26 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sica.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id_clase",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("nombre_clase", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "clase",
                "ordering": ["id_clase"],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id_cuenta",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nombre_cuenta", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "cuenta",
                "ordering": ["id_cuenta"],
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id_grupo",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("nombre_grupo", models.CharField(max_length=50)),
                (
                    "id_clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.clase",
                        verbose_name="Clase",
                    ),
                ),
            ],
            options={
                "db_table": "grupo",
                "ordering": ["id_grupo"],
            },
        ),
        migrations.CreateModel(
            name="OrdendeProduccion",
            fields=[
                (
                    "id_OrdendeProduccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombre_cliente",
                    models.CharField(max_length=50, verbose_name="Nombre"),
                ),
                (
                    "apellido_cliente",
                    models.CharField(max_length=50, verbose_name="Apellido"),
                ),
                (
                    "fecha_Actual",
                    models.DateField(
                        help_text="Consejo: <em>Presione en el calendario</em>.",
                        verbose_name="Fecha de Compra",
                    ),
                ),
                (
                    "numero_Pedido",
                    models.IntegerField(null=True, verbose_name="N° de Pedido "),
                ),
                (
                    "cantidad_Producto",
                    models.IntegerField(null=True, verbose_name="Cantidad de Producto"),
                ),
                (
                    "detalles_Pedido",
                    models.CharField(max_length=50, verbose_name="Observaciones"),
                ),
            ],
            options={
                "db_table": "ordedeProduccion",
                "ordering": ["id_OrdendeProduccion"],
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id_partida",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="N° de partida"
                    ),
                ),
                (
                    "descripcion_partida",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Descripcion"
                    ),
                ),
            ],
            options={
                "db_table": "partidas",
                "ordering": ["id_partida"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_Producto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_Producto",
                    models.CharField(max_length=50, verbose_name="Nombre"),
                ),
                ("precio_Producto", models.FloatField(verbose_name="Precio")),
            ],
            options={
                "db_table": "Producto",
                "ordering": ["id_Producto"],
            },
        ),
        migrations.CreateModel(
            name="SubCuenta",
            fields=[
                (
                    "id_subCuenta",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nombre_subCuenta", models.CharField(max_length=50)),
                (
                    "debe",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "haber",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "id_cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.cuenta",
                        verbose_name="Cuenta",
                    ),
                ),
            ],
            options={
                "db_table": "subCuenta",
                "ordering": ["id_subCuenta"],
            },
        ),
        migrations.CreateModel(
            name="TipoTransaccion",
            fields=[
                (
                    "id_tipoTransaccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_tipoTransaccion", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "TipoTransaccion",
            },
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_transaccionT",
                    models.DateField(
                        help_text="Consejo: <em>Presione en el calendario</em>.",
                        validators=[sica.models.validar_fecha],
                        verbose_name="Fecha de Transaccion",
                    ),
                ),
                (
                    "descripcion_transaccionT",
                    models.CharField(
                        max_length=80, null=True, verbose_name="Descripcion"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "id_clase",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.clase",
                        verbose_name="Clase",
                    ),
                ),
                (
                    "id_cuenta",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_grupo",
                        chained_model_field="id_grupo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.cuenta",
                        verbose_name="Cuenta",
                    ),
                ),
                (
                    "id_grupo",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_clase",
                        chained_model_field="id_clase",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.grupo",
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "id_partida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sica.partida"
                    ),
                ),
                (
                    "id_subCuenta",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_cuenta",
                        chained_model_field="id_cuenta",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.subcuenta",
                        verbose_name="Sub-Cuenta",
                    ),
                ),
                (
                    "id_tipoTransaccion",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.tipotransaccion",
                        verbose_name="Tipo de Transacción",
                    ),
                ),
            ],
            options={
                "db_table": "transaccion",
                "ordering": ["id_transaccion"],
            },
        ),
        migrations.CreateModel(
            name="Prorrateo",
            fields=[
                ("id_Prorrateo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "manodeObraIndirecta",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Mano de Obra Indirecta",
                    ),
                ),
                (
                    "alquiler",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Alquiler del local",
                    ),
                ),
                (
                    "segurosEquipo",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Seguro y Equipo",
                    ),
                ),
                (
                    "depreciacion",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Depreciacion",
                    ),
                ),
                (
                    "energia",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Energia Electrica",
                    ),
                ),
                (
                    "amortizacion",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amortizacion",
                    ),
                ),
                (
                    "otrosGastos",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Otros Gastos",
                    ),
                ),
                (
                    "totalCIF",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="CIF",
                    ),
                ),
                (
                    "aplicacionHMOD",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base HMOD",
                    ),
                ),
                (
                    "tasapredeterminadaCIF",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tasa CIF",
                    ),
                ),
                (
                    "id_OrdendeProduccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.ordendeproduccion",
                        verbose_name="N° Orden",
                    ),
                ),
            ],
            options={
                "db_table": "prorrateo",
                "ordering": ["id_Prorrateo"],
            },
        ),
        migrations.AddField(
            model_name="ordendeproduccion",
            name="producto_Orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sica.producto",
                verbose_name="Lista de Productos",
            ),
        ),
        migrations.CreateModel(
            name="ManodeObra",
            fields=[
                ("id_manodeObra", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_manodeObra",
                    models.DateField(
                        help_text="Consejo: <em>Presione en el calendario</em>.",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "horas_manodeObra",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "salario_manodeObra",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario por Hora",
                    ),
                ),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_OrdendeProduccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.ordendeproduccion",
                        verbose_name="N° Orden",
                    ),
                ),
            ],
            options={
                "db_table": "ManodeObra",
                "ordering": ["id_OrdendeProduccion"],
            },
        ),
        migrations.AddField(
            model_name="cuenta",
            name="id_grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sica.grupo",
                verbose_name="Grupo",
            ),
        ),
        migrations.CreateModel(
            name="CostosIndirectos",
            fields=[
                (
                    "id_costosIndirectos",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_costosIndirectos",
                    models.DateField(
                        help_text="Consejo: <em>Presione en el calendario</em>.",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "pagoManodeObra",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pago Mano de Obra",
                    ),
                ),
                (
                    "costoAplicado",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo Aplicado",
                    ),
                ),
                (
                    "id_OrdendeProduccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.ordendeproduccion",
                        verbose_name="N° Orden",
                    ),
                ),
                (
                    "id_Prorrateo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.prorrateo",
                        verbose_name="Prorrateo",
                    ),
                ),
            ],
            options={
                "db_table": "costosIndirectos",
                "ordering": ["id_costosIndirectos"],
            },
        ),
        migrations.CreateModel(
            name="Ajuste",
            fields=[
                ("id_ajuste", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_ajuste", models.DateField(auto_now_add=True)),
                (
                    "descripcion_ajuste",
                    models.CharField(
                        max_length=80, null=True, verbose_name="Descripcion"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "id_clase",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.clase",
                        verbose_name="Clase",
                    ),
                ),
                (
                    "id_cuenta",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_grupo",
                        chained_model_field="id_grupo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.cuenta",
                        verbose_name="Cuenta",
                    ),
                ),
                (
                    "id_grupo",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_clase",
                        chained_model_field="id_clase",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.grupo",
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "id_subCuenta",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="id_cuenta",
                        chained_model_field="id_cuenta",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.subcuenta",
                        verbose_name="Sub-Cuenta",
                    ),
                ),
                (
                    "id_tipoTransaccion",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sica.tipotransaccion",
                        verbose_name="Tipo de Transacción",
                    ),
                ),
            ],
            options={
                "db_table": "ajuste",
                "ordering": ["id_ajuste"],
            },
        ),
    ]
