# Generated by Django 3.2 on 2023-10-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendeproduccion',
            name='cantidad_Producto',
        ),
        migrations.RemoveField(
            model_name='prorrateo',
            name='alquiler',
        ),
        migrations.AlterField(
            model_name='ordendeproduccion',
            name='producto_Orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sica.producto', verbose_name='Lista de Servicios'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_Producto',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
