# Generated by Django 3.2 on 2023-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sica', '0002_auto_20231026_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeproduccion',
            name='precio_MateriaPrima',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
